name: docker

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/docker.yaml'
      - 'config/**'
      - 'Dockerfile'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker.yaml'
      - 'config/**'
      - 'Dockerfile'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Add Image Metadata"
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: xunholy/enemy-territory
          flavor: |
            latest=auto
          tags: |
            type=sha,
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=edge,branch=$repo.default_branch
          labels: |
            org.opencontainers.image.title=xUnholy ETLegacy Server

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
